import { Patient, StaffUser, PendingReport, RecentActivity, AuditLog } from './types';

export const INITIAL_STAFF_USERS: StaffUser[] = [
  {
    id: 'usr-1',
    name: 'Dr. Priya Raman, MD',
    role: 'doctor',
    title: 'Consultant Physician & Cardiologist',
    department: 'Internal Medicine',
    badgeNumber: 'DOC-8821',
  },
  {
    id: 'usr-2',
    name: 'Anitha M., RN',
    role: 'nurse',
    title: 'Senior Clinical Staff Nurse',
    department: 'Triage & Outpatient',
    badgeNumber: 'NRS-4309',
  },
  {
    id: 'usr-3',
    name: 'Rajan K.',
    role: 'admin',
    title: 'Health Systems Administrator',
    department: 'Hospital IT & Compliance',
    badgeNumber: 'ADM-1002',
  },
];

export const INITIAL_PATIENTS: Patient[] = [
  {
    id: 'PT-20481',
    name: 'Arun Kumar',
    age: 42,
    gender: 'Male',
    bloodGroup: 'B+',
    phone: '+91 98450 21984',
    email: 'arun.kumar@gmail.com',
    address: '42 Crescent Avenue, AI Campus Zone, Coimbatore',
    emergencyContact: 'Meena Kumar (Spouse) - +91 98450 21985',
    lastVisit: '12 Aug 2026',
    allergies: [
      {
        id: 'alg-1',
        allergen: 'Penicillin',
        severity: 'severe',
        reaction: 'Anaphylaxis & severe urticarial rash within 15 mins of administration',
        dateIdentified: '14 May 2018',
      },
    ],
    diagnoses: [
      {
        id: 'dx-1',
        condition: 'Type 2 Diabetes Mellitus',
        icdCode: 'E11.9',
        diagnosedYear: '2021',
        status: 'managed',
        department: 'Endocrinology',
        treatingDoctor: 'Dr. Priya Raman',
      },
      {
        id: 'dx-2',
        condition: 'Mild Essential Hypertension',
        icdCode: 'I10',
        diagnosedYear: '2023',
        status: 'active',
        department: 'Cardiology',
        treatingDoctor: 'Dr. Priya Raman',
      },
    ],
    medications: [
      {
        id: 'med-1',
        name: 'Metformin Hydrochloride',
        dosage: '500mg',
        frequency: 'twice daily',
        route: 'Oral (post meals)',
        startDate: '10 Jan 2021',
        status: 'active',
        prescribedBy: 'Dr. Priya Raman',
        department: 'Endocrinology',
        sourceSystem: 'Central Pharmacy Portal',
      },
      {
        id: 'med-2',
        name: 'Amlodipine Besylate',
        dosage: '5mg',
        frequency: 'once daily',
        route: 'Oral (morning)',
        startDate: '15 Mar 2023',
        status: 'active',
        prescribedBy: 'Dr. Priya Raman',
        department: 'Cardiology',
        sourceSystem: 'Central Pharmacy Portal',
      },
      {
        id: 'med-3',
        name: 'Atorvastatin',
        dosage: '10mg',
        frequency: 'once daily at bedtime',
        route: 'Oral',
        startDate: '12 Feb 2025',
        status: 'active',
        prescribedBy: 'Dr. S. K. Nair',
        department: 'Preventive Health',
        sourceSystem: 'Apollo Pharmacy Sync',
      },
    ],
    labResults: [
      {
        id: 'lab-1',
        testName: 'HbA1c (Glycated Hemoglobin)',
        category: 'Biochemistry',
        value: '6.8',
        unit: '%',
        referenceRange: '< 5.7% Normal, 5.7-6.4% Prediabetes, ≥ 6.5% Diabetes',
        status: 'normal',
        testDate: '10 Aug 2026',
        sourceSystem: 'Metropolis Lab Sys',
        notes: 'Well managed under Metformin therapy',
      },
      {
        id: 'lab-2',
        testName: 'Blood Pressure',
        category: 'Vitals',
        value: '138/88',
        unit: 'mmHg',
        referenceRange: '< 120/80 mmHg',
        status: 'elevated',
        testDate: '12 Aug 2026',
        sourceSystem: 'Triage Room 3 Vitals Monitor',
        notes: 'Stage 1 systolic borderline reading. Advised sodium restriction.',
      },
      {
        id: 'lab-3',
        testName: 'Total Serum Cholesterol',
        category: 'Biochemistry',
        value: '192',
        unit: 'mg/dL',
        referenceRange: '< 200 mg/dL Desirable',
        status: 'normal',
        testDate: '10 Aug 2026',
        sourceSystem: 'Metropolis Lab Sys',
        notes: 'Lipid profile stable on statin',
      },
      {
        id: 'lab-4',
        testName: 'Serum Creatinine',
        category: 'Biochemistry',
        value: '0.94',
        unit: 'mg/dL',
        referenceRange: '0.7 - 1.3 mg/dL',
        status: 'normal',
        testDate: '10 Aug 2026',
        sourceSystem: 'Metropolis Lab Sys',
        notes: 'eGFR > 90 mL/min/1.73m²',
      },
      {
        id: 'lab-5',
        testName: 'Fasting Blood Glucose',
        category: 'Biochemistry',
        value: '128',
        unit: 'mg/dL',
        referenceRange: '70 - 99 mg/dL Fasting',
        status: 'elevated',
        testDate: '10 Aug 2026',
        sourceSystem: 'Metropolis Lab Sys',
      },
    ],
    doctorNotes: [
      {
        id: 'note-1',
        authorName: 'Dr. Priya Raman',
        authorRole: 'Consultant Physician',
        department: 'Internal Medicine',
        date: '12 Aug 2026',
        category: 'Follow-up',
        content:
          'Patient advised to continue current medication and return for review in 4 weeks. Emphasized low sodium diet, 30 min daily brisk walking, and self-monitoring of blood pressure twice weekly.',
      },
      {
        id: 'note-2',
        authorName: 'Dr. Priya Raman',
        authorRole: 'Consultant Physician',
        department: 'Internal Medicine',
        date: '14 May 2025',
        category: 'Consultation',
        content:
          'Annual comprehensive diabetic screening. Fundus exam normal with no diabetic retinopathy. Peripheral pulses intact, sensation preserved. HbA1c adjusted target 6.5-7.0%.',
      },
    ],
    visits: [
      {
        id: 'vis-1',
        date: '12 Aug 2026',
        type: 'Routine Checkup',
        department: 'Internal Medicine',
        attendingPhysician: 'Dr. Priya Raman',
        reasonForVisit: 'Quarterly review for hypertension and diabetes follow-up',
        clinicalSummary:
          'Patient reported good compliance with Metformin and Amlodipine. No headaches, dizziness, or pedal edema noted.',
        vitals: {
          bloodPressure: '138/88',
          heartRate: 74,
          temperature: '98.4 °F',
          spO2: 99,
          glucose: '128 mg/dL',
        },
      },
      {
        id: 'vis-2',
        date: '14 May 2025',
        type: 'Outpatient',
        department: 'Cardiology',
        attendingPhysician: 'Dr. Priya Raman',
        reasonForVisit: 'Annual cardiovascular risk assessment',
        clinicalSummary:
          'ECG showed sinus rhythm, no ischemic ST changes. Advised continuing preventive lipid lowering.',
        vitals: {
          bloodPressure: '134/84',
          heartRate: 76,
          temperature: '98.6 °F',
          spO2: 98,
        },
      },
    ],
    vitals: {
      bloodPressure: '138/88',
      heartRate: 74,
      temperature: '98.4 °F',
      spO2: 99,
      bmi: 24.8,
      bloodSugar: '128 mg/dL',
    },
    siloSources: {
      emrSource: 'EMR A - Primary Care Clinic #4',
      labSource: 'Metropolis Lab Sys (Integrated)',
      pharmacySource: 'Central Hospital Pharmacy e-Prescribe',
      paperArchiveMigrated: true,
    },
  },
  {
    id: 'PT-10924',
    name: 'Divya S.',
    age: 34,
    gender: 'Female',
    bloodGroup: 'O+',
    phone: '+91 97890 34112',
    email: 'divya.s92@outlook.com',
    address: '18 Green Valley Towers, Peelamedu, Coimbatore',
    emergencyContact: 'Suresh R. (Brother) - +91 97890 34119',
    lastVisit: '16 Sep 2026',
    allergies: [
      {
        id: 'alg-2',
        allergen: 'Sulfa Drugs (Sulfonamides)',
        severity: 'severe',
        reaction: 'Erythema multiforme and facial swelling',
        dateIdentified: '22 Oct 2020',
      },
      {
        id: 'alg-3',
        allergen: 'Dust Mites & Seasonal Pollen',
        severity: 'mild',
        reaction: 'Allergic rhinitis & mild bronchospasm',
        dateIdentified: '05 Jan 2017',
      },
    ],
    diagnoses: [
      {
        id: 'dx-3',
        condition: 'Bronchial Asthma (Moderate Persistent)',
        icdCode: 'J45.40',
        diagnosedYear: '2019',
        status: 'active',
        department: 'Pulmonology',
        treatingDoctor: 'Dr. M. Varun',
      },
    ],
    medications: [
      {
        id: 'med-4',
        name: 'Budesonide + Formoterol Inhaler',
        dosage: '200mcg / 6mcg',
        frequency: '2 puffs twice daily',
        route: 'Inhalation',
        startDate: '16 Sep 2026',
        status: 'active',
        prescribedBy: 'Dr. M. Varun',
        department: 'Pulmonology',
        sourceSystem: 'Apollo Pharmacy Sync',
      },
      {
        id: 'med-5',
        name: 'Montelukast Sodium',
        dosage: '10mg',
        frequency: 'once daily at night',
        route: 'Oral',
        startDate: '16 Sep 2026',
        status: 'active',
        prescribedBy: 'Dr. M. Varun',
        department: 'Pulmonology',
        sourceSystem: 'Apollo Pharmacy Sync',
      },
    ],
    labResults: [
      {
        id: 'lab-6',
        testName: 'Peak Expiratory Flow Rate (PEFR)',
        category: 'Vitals',
        value: '380',
        unit: 'L/min',
        referenceRange: '400 - 450 L/min predicted',
        status: 'low',
        testDate: '16 Sep 2026',
        sourceSystem: 'Pulmonary Function Lab',
        notes: 'Improved by 18% post bronchodilator challenge.',
      },
      {
        id: 'lab-7',
        testName: 'Absolute Eosinophil Count (AEC)',
        category: 'Hematology',
        value: '460',
        unit: 'cells/mcL',
        referenceRange: '20 - 500 cells/mcL',
        status: 'normal',
        testDate: '16 Sep 2026',
        sourceSystem: 'Metropolis Lab Sys',
      },
    ],
    doctorNotes: [
      {
        id: 'note-3',
        authorName: 'Dr. M. Varun',
        authorRole: 'Pulmonologist',
        department: 'Pulmonology',
        date: '16 Sep 2026',
        category: 'Consultation',
        content:
          'Prescription updated 42 min ago. Stepped up inhaled corticosteroid combo due to seasonal coughing bouts. Demonstration of spacer technique confirmed good adherence.',
      },
    ],
    visits: [
      {
        id: 'vis-3',
        date: '16 Sep 2026',
        type: 'Outpatient',
        department: 'Pulmonology',
        attendingPhysician: 'Dr. M. Varun',
        reasonForVisit: 'Exacerbation of nocturnal dry cough',
        clinicalSummary: 'Bilateral mild expiratory wheeze heard in lower zones. No chest pain or fever.',
        vitals: {
          bloodPressure: '118/74',
          heartRate: 82,
          temperature: '98.2 °F',
          spO2: 97,
        },
      },
    ],
    vitals: {
      bloodPressure: '118/74',
      heartRate: 82,
      temperature: '98.2 °F',
      spO2: 97,
      bmi: 21.9,
    },
    siloSources: {
      emrSource: 'EMR B - City Chest Center',
      labSource: 'Metropolis Lab Sys (Integrated)',
      pharmacySource: 'MedPlus e-Portal',
      paperArchiveMigrated: false,
    },
  },
  {
    id: 'PT-33019',
    name: 'Ramesh Patel',
    age: 58,
    gender: 'Male',
    bloodGroup: 'A+',
    phone: '+91 94220 88102',
    email: 'ramesh.patel@pateltextiles.in',
    address: '102 Avinashi Road, Race Course, Coimbatore',
    emergencyContact: 'Gita Patel (Spouse) - +91 94220 88105',
    lastVisit: '16 Sep 2026',
    allergies: [],
    diagnoses: [
      {
        id: 'dx-4',
        condition: 'Coronary Artery Disease (s/p PTCA to LAD)',
        icdCode: 'Z95.5',
        diagnosedYear: '2026',
        status: 'managed',
        department: 'Interventional Cardiology',
        treatingDoctor: 'Dr. Priya Raman',
      },
      {
        id: 'dx-5',
        condition: 'Hyperlipidemia',
        icdCode: 'E78.5',
        diagnosedYear: '2022',
        status: 'managed',
        department: 'Cardiology',
        treatingDoctor: 'Dr. Priya Raman',
      },
    ],
    medications: [
      {
        id: 'med-6',
        name: 'Aspirin (Gastro-resistant)',
        dosage: '75mg',
        frequency: 'once daily',
        route: 'Oral (after lunch)',
        startDate: '10 Sep 2026',
        status: 'active',
        prescribedBy: 'Dr. Priya Raman',
        department: 'Cardiology',
        sourceSystem: 'Central Pharmacy Portal',
      },
      {
        id: 'med-7',
        name: 'Ticagrelor',
        dosage: '90mg',
        frequency: 'twice daily',
        route: 'Oral',
        startDate: '10 Sep 2026',
        status: 'active',
        prescribedBy: 'Dr. Priya Raman',
        department: 'Cardiology',
        sourceSystem: 'Central Pharmacy Portal',
      },
      {
        id: 'med-8',
        name: 'Rosuvastatin',
        dosage: '20mg',
        frequency: 'once daily at night',
        route: 'Oral',
        startDate: '10 Sep 2026',
        status: 'active',
        prescribedBy: 'Dr. Priya Raman',
        department: 'Cardiology',
        sourceSystem: 'Central Pharmacy Portal',
      },
    ],
    labResults: [
      {
        id: 'lab-8',
        testName: 'Troponin-I (High Sensitivity)',
        category: 'Cardiology',
        value: '12',
        unit: 'ng/L',
        referenceRange: '< 14 ng/L Normal',
        status: 'normal',
        testDate: '15 Sep 2026',
        sourceSystem: 'Hospital Central Lab',
      },
      {
        id: 'lab-9',
        testName: 'Post-Op 2D Echocardiography',
        category: 'Cardiology',
        value: 'LVEF 55%',
        unit: '',
        referenceRange: '50 - 70% Normal',
        status: 'normal',
        testDate: '15 Sep 2026',
        sourceSystem: 'Non-Invasive Cardiac Lab',
        notes: 'Good anterior wall motion post drug-eluting stent placement.',
      },
    ],
    doctorNotes: [
      {
        id: 'note-4',
        authorName: 'Dr. Priya Raman',
        authorRole: 'Interventional Cardiologist',
        department: 'Cardiology',
        date: '16 Sep 2026',
        category: 'Discharge',
        content:
          'Discharge summary added 1 hr ago. Patient successfully underwent uncomplicated PTCA to mid-LAD with 1 DES. Hemodynamically stable, puncture site clean and dry. Dual antiplatelet therapy prescribed for 12 months minimum. Cardiac rehabilitation scheduled in 2 weeks.',
      },
    ],
    visits: [
      {
        id: 'vis-4',
        date: '16 Sep 2026',
        type: 'Inpatient',
        department: 'Cardiology',
        attendingPhysician: 'Dr. Priya Raman',
        reasonForVisit: 'Elective angioplasty and post-procedure observation',
        clinicalSummary: 'Discharge cleared. Vitals completely normal.',
        vitals: {
          bloodPressure: '122/78',
          heartRate: 68,
          temperature: '98.4 °F',
          spO2: 99,
        },
      },
    ],
    vitals: {
      bloodPressure: '122/78',
      heartRate: 68,
      temperature: '98.4 °F',
      spO2: 99,
      bmi: 26.2,
    },
    siloSources: {
      emrSource: 'Cath Lab Enterprise Suite',
      labSource: 'Hospital Central Lab',
      pharmacySource: 'IP Pharmacy Inpatient Portal',
      paperArchiveMigrated: true,
    },
  },
  {
    id: 'PT-44102',
    name: 'Kavya Nair',
    age: 27,
    gender: 'Female',
    bloodGroup: 'AB-',
    phone: '+91 93441 77621',
    email: 'kavya.nair@techfirm.co',
    address: '67 Saravanampatti IT Corridor, Coimbatore',
    emergencyContact: 'Devika Nair (Mother) - +91 93441 77625',
    lastVisit: '16 Sep 2026',
    allergies: [
      {
        id: 'alg-4',
        allergen: 'Ibuprofen & NSAIDs',
        severity: 'moderate',
        reaction: 'Severe gastritis, abdominal cramping, and eyelid edema',
        dateIdentified: '11 Mar 2022',
      },
    ],
    diagnoses: [
      {
        id: 'dx-6',
        condition: "Hashimoto's Autoimmune Thyroiditis",
        icdCode: 'E06.3',
        diagnosedYear: '2024',
        status: 'active',
        department: 'Endocrinology',
        treatingDoctor: 'Dr. S. K. Nair',
      },
    ],
    medications: [
      {
        id: 'med-9',
        name: 'Levothyroxine Sodium',
        dosage: '75mcg',
        frequency: 'once daily 30m before breakfast',
        route: 'Oral',
        startDate: '14 Feb 2024',
        status: 'active',
        prescribedBy: 'Dr. S. K. Nair',
        department: 'Endocrinology',
        sourceSystem: 'Central Pharmacy Portal',
      },
    ],
    labResults: [
      {
        id: 'lab-10',
        testName: 'Serum TSH (Ultrasensitive)',
        category: 'Biochemistry',
        value: '5.2',
        unit: 'mIU/L',
        referenceRange: '0.4 - 4.2 mIU/L Normal',
        status: 'elevated',
        testDate: '14 Sep 2026',
        sourceSystem: 'Metropolis Lab Sys',
        notes: 'Mild TSH elevation, dosage titration scheduled.',
      },
      {
        id: 'lab-11',
        testName: 'Anti-TPO Antibodies',
        category: 'Biochemistry',
        value: '340',
        unit: 'IU/mL',
        referenceRange: '< 35 IU/mL Negative',
        status: 'elevated',
        testDate: '14 Sep 2026',
        sourceSystem: 'Metropolis Lab Sys',
      },
    ],
    doctorNotes: [
      {
        id: 'note-5',
        authorName: 'Dr. S. K. Nair',
        authorRole: 'Endocrinologist',
        department: 'Endocrinology',
        date: '16 Sep 2026',
        category: 'Follow-up',
        content:
          'New appointment booked 2 hr ago. Scheduled comprehensive thyroid ultrasound and dose review for Levothyroxine. Avoid NSAID analgesics.',
      },
    ],
    visits: [
      {
        id: 'vis-5',
        date: '16 Sep 2026',
        type: 'Routine Checkup',
        department: 'Endocrinology',
        attendingPhysician: 'Dr. S. K. Nair',
        reasonForVisit: 'Fatigue and quarterly thyroid level assessment',
        clinicalSummary: 'Thyroid gland non-tender, slight diffuse enlargement palpable.',
        vitals: {
          bloodPressure: '112/72',
          heartRate: 64,
          temperature: '98.1 °F',
          spO2: 99,
        },
      },
    ],
    vitals: {
      bloodPressure: '112/72',
      heartRate: 64,
      temperature: '98.1 °F',
      spO2: 99,
      bmi: 22.4,
    },
    siloSources: {
      emrSource: 'EMR A - Clinic #2',
      labSource: 'Metropolis Lab Sys (Integrated)',
      pharmacySource: 'Central Pharmacy Portal',
      paperArchiveMigrated: false,
    },
  },
  {
    id: 'PT-55210',
    name: 'Rajesh Menon',
    age: 65,
    gender: 'Male',
    bloodGroup: 'B-',
    phone: '+91 98840 55190',
    email: 'rajesh.menon@keralatrust.org',
    address: '89 Gandhipuram West, Coimbatore',
    emergencyContact: 'Vijay Menon (Son) - +91 98840 55194',
    lastVisit: '04 Sep 2026',
    allergies: [
      {
        id: 'alg-5',
        allergen: 'Cephalosporins (Cross-reactivity caution)',
        severity: 'moderate',
        reaction: 'Pruritus and maculopapular rash',
        dateIdentified: '19 Aug 2021',
      },
    ],
    diagnoses: [
      {
        id: 'dx-7',
        condition: 'Chronic Kidney Disease (Stage 2 Mild)',
        icdCode: 'N18.2',
        diagnosedYear: '2024',
        status: 'managed',
        department: 'Nephrology',
        treatingDoctor: 'Dr. K. Anbarasan',
      },
      {
        id: 'dx-8',
        condition: 'Bilateral Knee Osteoarthritis',
        icdCode: 'M17.0',
        diagnosedYear: '2020',
        status: 'active',
        department: 'Orthopedics',
        treatingDoctor: 'Dr. S. Chandran',
      },
    ],
    medications: [
      {
        id: 'med-10',
        name: 'Telmisartan',
        dosage: '40mg',
        frequency: 'once daily',
        route: 'Oral (morning)',
        startDate: '10 Jan 2024',
        status: 'active',
        prescribedBy: 'Dr. K. Anbarasan',
        department: 'Nephrology',
        sourceSystem: 'Central Pharmacy Portal',
      },
      {
        id: 'med-11',
        name: 'Paracetamol',
        dosage: '650mg',
        frequency: 'as needed for joint pain (max 3/day)',
        route: 'Oral',
        startDate: '12 Jun 2023',
        status: 'active',
        prescribedBy: 'Dr. S. Chandran',
        department: 'Orthopedics',
        sourceSystem: 'Central Pharmacy Portal',
      },
    ],
    labResults: [
      {
        id: 'lab-12',
        testName: 'Serum Creatinine',
        category: 'Biochemistry',
        value: '1.45',
        unit: 'mg/dL',
        referenceRange: '0.7 - 1.3 mg/dL',
        status: 'elevated',
        testDate: '04 Sep 2026',
        sourceSystem: 'Hospital Central Lab',
      },
      {
        id: 'lab-13',
        testName: 'Estimated GFR (CKD-EPI)',
        category: 'Biochemistry',
        value: '54',
        unit: 'mL/min/1.73m²',
        referenceRange: '> 60 mL/min/1.73m²',
        status: 'low',
        testDate: '04 Sep 2026',
        sourceSystem: 'Hospital Central Lab',
        notes: 'Stage 3a border. Strictly avoid NSAIDs and nephrotoxic contrast.',
      },
    ],
    doctorNotes: [
      {
        id: 'note-6',
        authorName: 'Dr. K. Anbarasan',
        authorRole: 'Nephrologist',
        department: 'Nephrology',
        date: '04 Sep 2026',
        category: 'Consultation',
        content:
          'Reinforced strict avoidance of NSAIDs due to declining renal function. Continue renal-protective Telmisartan. Hydration target 2.5L/day. Renal ultrasound scheduled next month.',
      },
    ],
    visits: [
      {
        id: 'vis-6',
        date: '04 Sep 2026',
        type: 'Outpatient',
        department: 'Nephrology',
        attendingPhysician: 'Dr. K. Anbarasan',
        reasonForVisit: 'Biannual renal profile and joint pain management review',
        clinicalSummary: 'No peripheral edema, chest clear. BP controlled.',
        vitals: {
          bloodPressure: '126/80',
          heartRate: 72,
          temperature: '98.5 °F',
          spO2: 98,
        },
      },
    ],
    vitals: {
      bloodPressure: '126/80',
      heartRate: 72,
      temperature: '98.5 °F',
      spO2: 98,
      bmi: 27.1,
    },
    siloSources: {
      emrSource: 'Paper Archive Migrated + EMR C',
      labSource: 'Hospital Central Lab',
      pharmacySource: 'Central Pharmacy Portal',
      paperArchiveMigrated: true,
    },
  },
];

export const INITIAL_PENDING_REPORTS: PendingReport[] = [
  {
    id: 'rep-101',
    testName: 'Comprehensive Blood Panel',
    department: 'Pathology & Hematology',
    roomOrLocation: 'Room 4',
    patientId: 'PT-20481',
    patientName: 'Arun Kumar',
    requestedAt: 'Today, 08:30 AM',
    priority: 'Urgent',
    status: 'Pending Analysis',
  },
  {
    id: 'rep-102',
    testName: 'Weight-bearing Knee X-Ray',
    department: 'Radiology / Ortho Dept',
    roomOrLocation: 'Ortho Dept (Bldg B)',
    patientId: 'PT-55210',
    patientName: 'Rajesh Menon',
    requestedAt: 'Today, 09:15 AM',
    priority: 'Routine',
    status: 'Awaiting Sign-off',
  },
  {
    id: 'rep-103',
    testName: 'Contrast MRI Review',
    department: 'Neurosciences',
    roomOrLocation: 'Neuro Imaging Wing',
    patientId: 'PT-33019',
    patientName: 'Ramesh Patel',
    requestedAt: 'Today, 10:05 AM',
    priority: 'Stat',
    status: 'Ready for Review',
  },
  {
    id: 'rep-104',
    testName: 'Thyroid Ultrasound Doppler',
    department: 'Endocrine Ultrasound',
    roomOrLocation: 'Room 12',
    patientId: 'PT-44102',
    patientName: 'Kavya Nair',
    requestedAt: 'Today, 11:00 AM',
    priority: 'Routine',
    status: 'Pending Analysis',
  },
];

export const INITIAL_RECENT_ACTIVITIES: RecentActivity[] = [
  {
    id: 'act-1',
    patientName: 'Arun Kumar',
    patientId: 'PT-20481',
    action: 'Lab report uploaded (Biochemistry Panel)',
    timeAgo: '10 min ago',
    type: 'lab',
  },
  {
    id: 'act-2',
    patientName: 'Divya S.',
    patientId: 'PT-10924',
    action: 'Prescription updated (Budesonide + Formoterol)',
    timeAgo: '42 min ago',
    type: 'prescription',
  },
  {
    id: 'act-3',
    patientName: 'Ramesh P.',
    patientId: 'PT-33019',
    action: 'Discharge summary added (Post-PTCA Protocol)',
    timeAgo: '1 hr ago',
    type: 'discharge',
  },
  {
    id: 'act-4',
    patientName: 'Kavya N.',
    patientId: 'PT-44102',
    action: 'New appointment booked (Endocrine Follow-up)',
    timeAgo: '2 hr ago',
    type: 'appointment',
  },
  {
    id: 'act-5',
    patientName: 'Rajesh Menon',
    patientId: 'PT-55210',
    action: 'Vitals & renal function synced from Central Lab',
    timeAgo: '3 hr ago',
    type: 'vitals',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-01',
    timestamp: '2026-09-16 09:10:14',
    userId: 'usr-1',
    userName: 'Dr. Priya Raman, MD',
    userRole: 'doctor',
    action: 'VIEW_RECORD',
    patientId: 'PT-20481',
    patientName: 'Arun Kumar',
    details: 'Accessed Unified EHR Overview to review diabetes and BP trends',
    ipAddress: '192.168.1.104 (Clinical Workstation 4)',
  },
  {
    id: 'log-02',
    timestamp: '2026-09-16 08:32:41',
    userId: 'usr-2',
    userName: 'Anitha M., RN',
    userRole: 'nurse',
    action: 'UPLOAD_LAB',
    patientId: 'PT-20481',
    patientName: 'Arun Kumar',
    details: 'Logged morning blood glucose and vitals check',
    ipAddress: '192.168.1.112 (Triage iPad Station)',
  },
  {
    id: 'log-03',
    timestamp: '2026-09-16 08:18:22',
    userId: 'usr-1',
    userName: 'Dr. Priya Raman, MD',
    userRole: 'doctor',
    action: 'UPDATE_PRESCRIPTION',
    patientId: 'PT-10924',
    patientName: 'Divya S.',
    details: 'Adjusted inhaler regimen after bronchodilator challenge review',
    ipAddress: '192.168.1.104 (Clinical Workstation 4)',
  },
  {
    id: 'log-04',
    timestamp: '2026-09-16 07:45:00',
    userId: 'usr-3',
    userName: 'Rajan K.',
    userRole: 'admin',
    action: 'REGISTER_PATIENT',
    patientId: 'PT-44102',
    patientName: 'Kavya Nair',
    details: 'Synchronized patient record from legacy paper archive into Unified EHR',
    ipAddress: '192.168.1.201 (IT Admin Terminal)',
  },
  {
    id: 'log-05',
    timestamp: '2026-09-16 07:12:05',
    userId: 'usr-1',
    userName: 'Dr. Priya Raman, MD',
    userRole: 'doctor',
    action: 'CROSS_CHECK_AI',
    patientId: 'PT-20481',
    patientName: 'Arun Kumar',
    details: 'Ran AI Clinical Safety Cross-Check (Penicillin allergy vs prospective prescriptions)',
    ipAddress: '192.168.1.104 (Clinical Workstation 4)',
  },
];
